deploy:
  provider: heroku
  api_key:
    secure: CizZ5bLNeqm/hA+f+OjmGY8EXWCKY8DkXJX2Q02eDMLZ7GL6VjxpOiMv8wd4uL3t9/4j+gPGz07XtFXjhh1OfzKjv+xr5+gXNHvj6vZqbP3TDi2tjzSDBDuBjyJSxYN3RPhv9RQIZ/hGbE85t4M18HWrHqrXINfk5yQZj/6e6TNQHEPP4dof0uv7rv74hb5xJrFEIHyNGkpUK1CanYYBS5IB3TUVQ5jGTzOze17EUqHGqYPtslhxvT4r3uFJbUDNmYFNFHSpQD72D0kcKtlBYhyQold2jrqQB8eW8aQv+9SDJbXBw/HqV7F17UCZZ3E8aaGwCpYr1SSw5LlsWqhpB/13/mc7/evnw7umjxs/qnqogxpUqeP7D5O560Mjl0DlKIUiQyXAkeyzwlJ6k5Hz3VnB+rY68amkwQMcMuFZtSgw1lJQH72p6pHkI/KYhULiZZfpzdwzf8GWZoKIsvgIOhyZSwhZQv2ltlzPjWXTYqnEZEjzE9d5p9WSE3OpGNKfKlcfDt0IpNx8Bn6IyRsXxitcoxOEgmZPYI9czupY4sbZTNhBRnHnKEIE/79upZmAFMNWHXGA30GM6J+z80e02hG7i5CTK1T8uIZJSeU6OTsOTHUAEfOnO3ySIua28qVVhqv6UpdGTsvSOXEZdzqsB/crdo4Kjz833Rr2uUihV4o=
  app: safe-atoll-46112
  on:
    repo: ianmcdermott/blog-app-mongoose-challenge-solution
